server:
  port: 12013

spring:
  application:
    name: turbine-service,SERVICE-ZUUL

turbine:
  combine-host-port: true
  # 配置需要监控的服务名,会通过eureka获取
  app-config: ribbon-client
  # 集群的服务名
  cluster-name-expression: new String("default")
  aggregator:
    cluster-config: default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:12000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

hystrix:
  dashboard:
    # hystrix.dashboard.proxy-stream-allow-list 配置用于指定允许代理的Hystrix流（stream）地址。
    # 它的主要作用是为了安全起见，明确哪些主机或URL可以作为Hystrix Dashboard的代理目标。
    proxy-stream-allow-list: "*"