server:
  port: 11007

spring:
  elasticsearch:
    uris: http://192.168.3.101:9200
#    username: elastic
#    password: Q_N3Ja+RBs3xHLhOdKz-
  main:
    allow-bean-definition-overriding: true


#logging:
#  level:
#    root: debug

