---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 2024/12/26 16:10
---

local http = require "resty.http"

-- 创建 HTTP 客户端实例
local httpc = http.new()

-- 设置请求参数
local url = "http://localhost:10090/decode-token"
local params = {
    token = "5tsc94g3L683SI1exglKVee3YmmPdQbxComoEy0ADMaVgYSpwipXWi_VF9Hx49MzLWYwGeDiWRA"
}

-- 将参数转换为查询字符串
local query_string = ngx.encode_args(params)

-- 发送 GET 请求
local res, err = httpc:request_uri(url, {
    method = "GET",
    query = query_string,
    headers = {
        ["Content-Type"] = "application/x-www-form-urlencoded",
    },
})

-- 检查响应
if not res then
    ngx.say("Failed to request: ", err)
    return
end

-- 输出响应结果
ngx.say("Status: ", res.status)
ngx.say("Response: ", res.body)
