---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 2024/12/24 10:49
---

local http = require("socket.http")

local response, status = http.request("http://example.com")
if status == 200 then
    print(response)
else
    print("HTTP request failed with status code: " .. status)
end
