---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 2024/12/27 10:27
---


local http = require("socket.http")
local ltn12 = require("ltn12")

-- 设置请求 URL 和请求体
local url = "http://example.com/api"
local request_body = "param1=value1&param2=value2"

-- 创建响应体表
local response_body = {}

-- 发送 POST 请求
local res, code, response_headers, status = http.request{
    url = url,
    method = "POST",
    source = ltn12.source.string(request_body),
    headers = {
        ["Content-Type"] = "application/x-www-form-urlencoded",
        ["Content-Length"] = tostring(#request_body)
    },
    sink = ltn12.sink.table(response_body)
}

-- 检查响应
if not res then
    print("Failed to request: ", code)
    return
end

-- 输出响应结果
print("Status: ", status)
print("Response: ", table.concat(response_body))
