---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 2024/12/24 10:54
---

local luasql = require "luasql.mysql"

local env = assert(luasql.mysql(), "Failed to create MySQL environment")

if env then
    print("luasql.mysql 已安装并可用")
else
    print("luasql.mysql 未安装或不可用")
end

local conn, err = env:connect("test", "root", "123456", "localhost", 3306)
if not conn then
    -- 这里报错 MySQL: Client does not support authentication protocol requested by server; consider upgrading MySQL clien�����X
    -- mysql8 之前的版本中加密规则是 mysql_native_password, 而在mysql8之后, 加密规则是 caching_sha2_password
    --
    print("Failed to connect to database: " .. err)
else
    print("Successfully connected to database")
end

-- 确保在连接成功后再执行查询操作
if conn then
    local cursor = assert(conn:execute("SELECT * FROM employees"), "Failed to execute query")
    local row = cursor:fetch({}, "a")
    while row do
        print(string.format("id: %s, name: %s", row.employee_number, row.last_name))
        row = cursor:fetch(row, "a")
    end

    cursor:close()
    conn:close()
end

env:close()

