---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 2024/12/24 12:09
---

local luasql = require "luasql.postgres"

local env = assert(luasql.postgres(), "Failed to create PostgreSQL environment")

if env then
    print("luasql.postgres 已安装并可用")
else
    print("luasql.postgres 未安装或不可用")
end

local conn, err = env:connect("bigdata", "postgres", "cquissE1!", "192.168.3.222", 5432)
-- conn=env:connect("数据库名","用户名","密码","IP地址","端口")
if not conn then
    print("Failed to connect to database: " .. err)
else
    print("Successfully connected to database")
end


local cursor = assert(conn:execute("SELECT * FROM scenarios_target limit 1"), "Failed to execute query")
local row = cursor:fetch({}, "a")
while row do
    print(string.format("id: %s", row.id))
    row = cursor:fetch(row, "a")
end

cursor:close()
conn:close()
env:close()
