---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 2024/12/27 18:06
---

local plugin_name = "custom-limit-rsp"
local core = require("apisix.core")
local cjson = require "cjson"

local schema = {

}

local _M = {
    version = 0.1,
    priority = 0,
    name = plugin_name,
    schema = schema
}

function _M.check_schema(conf)
    return core.schema.check(schema, conf)
end


-- 在 body_filter 阶段处理响应体
function _M.body_filter(conf, ctx)
    local chunk, eof = ngx.arg[1], ngx.arg[2]

    -- 读取和处理响应体
    if chunk then
        -- 将响应体拼接起来
        ctx.buffered = (ctx.buffered or "") .. chunk
    end

    -- 如果是响应体的最后一个块，解析 JSON 数据
    if eof then
        core.log.warn("Full response body: ", ctx.buffered)

        -- 解析 JSON 数据
        local json_data, err = cjson.decode(ctx.buffered)
        if not json_data then
            core.log.error("Failed to decode JSON: ", err)
            return
        end

        -- 处理解析后的 JSON 数据
        core.log.warn("Parsed JSON: ", core.json.encode(json_data))

        -- 你可以在这里对 JSON 数据进行进一步处理
    end
end

return _M

