logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: oauth-service
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.102:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456

server:
  #  servlet:
  #    context-path: /uaa
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.102:10001/eureka/

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

common:
  security:
    default:
      websecurity: true
    userservice:
      strategy: database