logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: oauth-service
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  security:
    user:
      name: admin
      password: 1

server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.102:10001/eureka/