---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by h1123.
--- DateTime: 2025/7/16 15:03
---


package.path = package.path .. ";~/redis-lua/src/?.lua"--redis.lua 所在目录
local json_encode = require "cjson" .encode
local redis = require("redis")
local reds, err = redis.connect('127.0.0.1', 6379)

local key = string.format("dragon:boat:festival:date:%s", os.date('%Y%m%d'))-- 排行榜key

local endtime = 1623600000-- 活动结束时间
local value = 9999-- 用户增加分数值
local sufix = endtime - os.time()-- 用户更新分数时间距离结束时间的差值
local user_id = 1001-- 用户id也就是有序集合的 field

local diff = 5 - string.len(sufix)-- 计算时间戳差值长度是否小于5 因为是每天排行榜 所以 最大的时间差为 86400


if diff < 5 then
    for i = 1, diff do
        sufix = 0 .. sufix
    end
end

local score = value .. sufix-- 组合成新的值
local res, err = reds:zadd(key, score, user_id)

print(sufix)
print(res)
print(key)