# ========== 数据库配置 ==========
spring:
  datasource:
    url: jdbc:mysql://192.168.3.102:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: "123456"  # 密码建议使用引号包裹
    # 连接池配置（可选）
    # type: com.zaxxer.hikari.HikariDataSource
    # hikari:
    #   maximum-pool-size: 10
    #   connection-timeout: 30000
  redis:
    host: 192.168.3.102  # Redis服务器地址
    port: 6379           # Redis端口
    password: "123456"   # Redis密码
    # 哨兵模式配置（已注释）
    # sentinel:
    #   master: mymaster
    #   nodes: 1.15.232.5:26379,1.15.232.5:26380,1.15.232.5:26381
    # 连接池配置（可选）
    # lettuce:
    #   pool:
    #     max-active: 8
    #     max-idle: 8
    #     min-idle: 0
    # timeout: 5000  # 连接超时(ms)

# ========== MyBatis 配置 ==========
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL日志打印到控制台
  mapper-locations: classpath:mapper/*Mapper.xml  # Mapper XML文件路径

# ========== Redis 配置 ==========