#!/bin/bash
#chkconfig:2345 61 61

export HOME=/root/rabbit/rabbitmq_server-3.8.15
export PATH=$PATH:/root/rabbit/rabbitmq_server-3.8.15/sbin

cd /root/rabbit/rabbitmq_server-3.8.15

case "$1" in
    start)
    echo "Starting RabbitMQ ..."
    rabbitmq-server  -detached
    ;;
stop)
    echo "Stopping RabbitMQ ..."
    rabbitmqctl stop
    ;;
status)
    echo "Status RabbitMQ ..."
    rabbitmqctl status
    ;;
restart)
    echo "Restarting RabbitMQ ..."
    rabbitmqctl stop
    rabbitmq-server  restart
    ;;

*)
    echo "Usage: $prog {start|stop|status|restart}"
    ;;
esac
exit 0