spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: http://httpbin.org:80
          predicates:
            - Query=red, gree.
#
# Query 谓词指定了当请求的查询参数中包含 red 并且这个 red得值必须是 gree. (gree加一个字符)