server:
  port: 11007

spring:
  profiles:
    active: db,redis
  main:
    allow-circular-references: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: debug
    org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate: debug