server:
  port: 10002
  ssl:
    # Spring Boot 启用 Https, 密钥文件是通过 keytool -keystore mykeys.jks -genkey -alias tomcat -keyalg RSA 这个生成的
    key-store: classpath:mykeys.jks
    key-store-password: 123456
    key-password: 123456

spring:
  application:
    name: keeping
  profiles:
    active: dev1,db,mq,mvc,redis,zk
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
    livereload:
      enabled: false
      port: 35729

# MyBatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml

# PageHelper
pagehelper:
  auto-runtime-dialect: true
  page-size-zero: true

# Custom Config
done:
  time:
    enable: true
greeting:
  welcome: "You are using ${spring.application.name}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

app:
  config:
    name: Myapp
    max-requests: 100
