server:
  port: 11010

spring:
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://192.168.80.128:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&connectionCollation=utf8mb4&rewriteBatchedStatements=true
    username: root
    password: 123456

# mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: session
    cache-enabled: true
  mapper-locations: classpath:mapper/*.xml


# pagehelper
pagehelper:
  auto-runtime-dialect: true
  page-size-zero: true

# log config
#logging:
#  level:
#    root: DEBUG
#    org:
#      mybatis:
#        spring:
#          transaction:
#            SpringManagedTransaction: DEBUG
#      springframework:
#        data:
#          redis: DEBUG
#      hulei:
#        springboot:
#          tkmybatis:
#            mapper:
#              EmployeeMapper: debug
#    com:
#      hundsun:
#        demo:
#          springboot:
#            mapper: debug