server:
  port: 10018

spring:
  application:
    name: service-gateway
  profiles:
    active: redis-connect,eureka
  main:
    allow-circular-references: true
    web-application-type: reactive

logging:
  level:
    root: info

# 以下是注释部分
# ignore:
#   whites:
#     - /search/*
#   loginUrl: /security/login
#   logoutUrl: /security/logout