server:
  port: 10015
spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: 192.168.3.102
      port: 8500

management:
  endpoints:
    web:
      exposure:
        include: '*'