server:
  port: 10015
spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: 192.168.3.102
      port: 8500
      discovery:
        # 服务在 Consul 注册中心中的名称，设置为 consul-provider。
        service-name: ${spring.application.name}
        # instanceId 是一个可选属性，允许你自定义服务实例的ID。你可以利用Spring表达式语言（SpEL）来构建一个复杂的ID。例如，包括应用IP、应用实例ID和一些随机值。
        instance-id: ${spring.application.name}:${server.port}
        # 定义健康检查的相对路径 以 / 开头的路径 (如 /actuator/health) 当服务使用标准端口和协议时
        # 而 health-check-url 定义完整的健康检查 URL，(如 http://${ip}:${port}/custom/health) 需要自定义协议、端口或特殊路径时
        health-check-path: /actuator/health
        health-check-interval: 30s
        # 优先以 ip 注册
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always