server:
  port: 11009

spring:
  profiles:
    active: db,mq
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  # mybatis configuration options (commented out)
  # configuration:
  #   local-cache-scope: statement
  #   cache-enabled: true

# mybatis-plus settings (commented out)
# mybatis-plus:
#   configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#   mapper-locations: classpath:mapper/*.xml
#   configuration:
#     local-cache-scope: statement
#     cache-enabled: true

pagehelper:
  auto-runtime-dialect: true
  page-size-zero: true

#logging:
#  level:
#    root: DEBUG
#    org:
#      mybatis:
#        spring:
#          transaction:
#            SpringManagedTransaction: DEBUG
#    org.springframework.data.redis: DEBUG
#    com.hundsun.demo.springboot.mapper: debug