# Spring Redis Config
spring:
  redis:
    host: localhost
    port: 6379
    # password: 123456
    connect-timeout: 5000

  # Sentinel Config
  # redis:
  #   sentinel:
  #     master: test
  #     nodes: 192.168.80.128:26379,192.168.80.129:26379,192.168.80.130:26379
  #     password: 123456