server:
  port: 10019

spring:
  application:
    # 服务名
    name: cloud-consumer
  main:
    # 允许循环依赖
    allow-circular-references: true

# 服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.102:10001/eureka/