server:
  # 0 表示随机端口
  port: 9999
  ssl:
    key-store: classpath:myclientkeystore.jks
    key-store-password: 123456
    key-password: 123456
    enabled: true

spring:
  application:
    name: keeping
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      # exclude: '**/static/**','**/*.js','**/*.html'
    livereload:
      enabled: false
      port: 35729
  mail:
    host: smtp.qq.com
    port: 465
    username: 1244171986@qq.com
    password: ghehgzvlqptigfjf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html

# logging:
#   level:
#     root: DEBUG
#     org.mybatis.spring.transaction.SpringManagedTransaction: DEBUG
#     org.springframework.data.redis: DEBUG
#     com.hundsun.demo.springboot.mapper: debug

# custom config
done:
  time:
    enable: true
greeting:
  welcome: You are using ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

# router prefix
# server:
#   servlet:
#     context-path: /api

app:
  config:
    name: Myapp
    max-requests: 100
jsch:
  ssh-host: 192.168.3.233
  ssh-port: 22
  ssh-username: root
  ssh-password: 2Kryspr!
  upstream-config-path: /usr/local/nginx/conf/upstream
  nginx-bin-path: /usr/local/nginx/sbin
  nginx-config-path: /usr/local/nginx/conf


knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: xiaoymin@foxmail.com
    concat: 八一菜刀
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.knife4j.demo.new3

