server:
  port: 11002
spring:
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&connectionCollation=utf8mb4&rewriteBatchedStatements=true&useCursorFetch=true
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
    #configuration:
    #local-cache-scope: statement
  #cache-enabled: true
pagehelper:
  auto-runtime-dialect: true
  page-size-zero: true
    #log config
    #logging:
    #level:
    #root: DEBUG
    #org.mybatis.spring.transaction.SpringManagedTransaction: DEBUG
    #org.springframework.data.redis: DEBUG
  #com.hundsun.demo.springboot.mapper: debug
done:
  time:
    enable: true
