server:
  port: 10019

spring:
  application:
    # 服务名
    name: spring-cloud-loadbalancer
  main:
    # 允许循环依赖
    allow-circular-references: true

# 服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:12001/eureka/