spring:
  rabbitmq:
    addresses: 192.168.3.102
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    # none	不开启发布确认（默认值）
    # correlated	开启 简单 Confirm，RabbitTemplate 会通过 CorrelationData 跟踪消息
    # simple	开启 基础 Confirm，内部基于 channel-level 的 ConfirmCallback，兼容性好但功能弱一些
    publisher-confirm-type: correlated
    publisher-returns: true         # 开启发布者退回通知
    listener:
      simple:
        acknowledge-mode: manual    # 手动确认消息
        prefetch: 1                 # 每次从 RabbitMQ 服务器读取的未确认消息数（默认为 250）