logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: service-auth
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.80.128:3306/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456

server:
  servlet:
    context-path: /uaa
  port: 10020


#security:
#  oauth2:
#    resource:
#      filter-order: 3
#  basic:
#    enabled: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
