server:
  port: 10009

spring:
  profiles:
    active: db,redis,zk,mvc
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://192.168.3.102:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&connectionCollation=utf8mb4&rewriteBatchedStatements=true
    username: root
    password: 123456

logging:
  level:
    org:
      springframework.jdbc.core.JdbcTemplate: debug
