##################################  web 服务器相关的配置  ##################################

server:
  # 0 表示随机端口
  port: 9998
#  ssl:
#    key-store: classpath:myclientkeystore.jks
#    key-store-password: 123456
#    key-password: 123456
#    enabled: true


##################################  spring 相关  ##################################
spring:
  application:
    name: keeping
  main:
    allow-circular-references: true
  # spring mvc
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://192.168.3.102:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&connectionCollation=utf8mb4&rewriteBatchedStatements=true
    username: root
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl