
########################################## 单机节点 ###########################################
# 配置 redis 单节点配置
spring:
  redis:
    host: 192.168.3.102
    port: 6379
#    username: default
    password: 123456
    timeout: 5000  # 连接超时时间（毫秒）
    database: 0    # 使用的 Redis 数据库索引



########################################## 集群配置 ###########################################
# redis 集群配置
# 这里预设有6个redis示例组成的redis集群，从6380到6385五个实例，3主3从的配置
#spring:
#  redis:
#    cluster:
#      # 配置集群节点，这里可以选择性配置，连接上之后会自动拉去集群的信息配置
#      # 但是不建议，配置多个可以避免单节点宕机后导致的服务启动失败
#      nodes:
#        - 192.168.3.102:6380
#        - 192.168.3.102:6381
#        - 192.168.3.102:6382
#      max-redirects: 3  # 最大重定向次数
#    lettuce:
#      pool:
#        max-active: 8    # 最大连接数
#        max-idle: 8      # 最大空闲连接数
#        min-idle: 0      # 最小空闲连接数
#        max-wait: -1ms   # 连接等待时间（负数表示无限等待）
#    timeout: 5000ms     # 连接超时时间
#    password: 123456



########################################## 主从架构时配置哨兵 ###########################################
# redis哨兵集群配置，配置哨兵节点后，每个哨兵都可以进行任意redis的操作
#spring:
#  redis:
#    # 哨兵模式配置
#    sentinel:
#      master: local-master  # Sentinel 里配置的 master 名称
#      nodes:
#        - 192.168.3.102:26386
#        - 192.168.3.102:26387
#        - 192.168.3.102:26388
##      password: 123456
#    # 连接池配置（可选）
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#    password: 123456