## 配置 redis 单节点配置
#spring:
#  redis:
#    host: 192.168.3.102
#    port: 6379
##    username: default
#    password: 123456
#    timeout: 5000  # 连接超时时间（毫秒）
#    database: 0    # 使用的 Redis 数据库索引


# redis 集群配置
spring:
  redis:
    cluster:
      nodes:
        - 192.168.3.102:6380
        - 192.168.3.102:6381
        - 192.168.3.102:6382
      max-redirects: 3  # 最大重定向次数
    lettuce:
      pool:
        max-active: 8    # 最大连接数
        max-idle: 8      # 最大空闲连接数
        min-idle: 0      # 最小空闲连接数
        max-wait: -1ms   # 连接等待时间（负数表示无限等待）
    timeout: 5000ms     # 连接超时时间
    password: 123456
