server:
  port: 12002

eureka:
  instance:
    prefer-ip-address: true
    hostname: peer2
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone:
        - http://peer1:12001/eureka/
        - http://peer2:12002/eureka/
        - http://peer3:12003/eureka/
