server:
  port: 12000

eureka:
  instance:
    # 此配置项指定 Eureka 实例在注册时是否优先使用 IP 地址而不是主机名
    prefer-ip-address: true
    # 此项配置定义了 Eureka 实例的主机名。在这里被设置为 localhost，表示该实例会使用本机作为主机名。
    hostname: localhost
  client:
    # 该配置项指示该服务是否应向 Eureka 注册。如果设置为 false，则该服务不会向 Eureka 注册自己。
    register-with-eureka: false
    # 此配置项指示该服务是否应从 Eureka 获取服务注册表。如果设置为 false，该服务不会尝试从 Eureka 获取服务列表。
    fetch-registry: false
    # 该配置定义了 Eureka 服务器的 URL。这是 Eureka 客户端与 Eureka 服务器之间的连接地址。
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/