server:
  port: 10000

spring:
  application:
    name: service-gateway
  profiles:
    active: redis-connect,eureka,default-router
  main:
    allow-circular-references: true
    web-application-type: reactive
management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  level:
    root: info

# 以下是注释部分
# ignore:
#   whites:
#     - /search/*
#   loginUrl: /security/login
#   logoutUrl: /security/logout