spring:
  cloud:
    gateway:
      routes:
        - id: my_route
          uri: lb://eureka-client
          predicates:
            - Path=/eureka-client/**
          filters:
            - name: SentinelGatewayFilter
              args:
                resource: my_route_limit