server:
  port: 10000

spring:
  application:
    name: gateway
  profiles:
    active: default-router,eureka,security,redis-limit-config
  main:
    allow-circular-references: true
    web-application-type: reactive
  redis:
    host: 192.168.3.102
    port: 6379
    database: 0
    password: 123456


management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: info