#spring:
#  application:
#    name: config-client
#  cloud:
#    config:
#      fail-fast: true
#      discovery:
#        enabled: true
#        service-id: config-server
#  profiles:
#    active: dev
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9100/eureka/
#server:
#  port: 9161


