spring:
  profiles:
    active: native
  rabbitmq:
    host: 192.168.3.102
    port: 5672
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
