spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: http://httpbin.org:80
          predicates:
            - Cookie=name,value

# cookie中必须包含指定的参数才能通过的断言
# postman请求header里添加cookie
# key为Cookie  value为name=value