spring:
  cloud:
    gateway:
      routes:
        - id: my_route
          uri: https://www.douyu.com
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
#            -

#在这个例子中：
#- `id` 属性是路由的唯一标识符。
#- `uri` 指定了请求应该转发到的下游服务地址。
#- `predicates` 部分定义了请求必须满足的条件来匹配这条路由，上例中的`Path=/api/service/**`意味着只有路径以`/api/service/`开头的请求会匹配这条路由。
#- `filters` 部分允许对请求/响应进行额外处理，在这个例子中使用了`RewritePath`过滤器，它将路径中匹配正则表达式`/api/service/(?<segment>.*)`的部分重新写为`/$\{segment}`。这里`segment`是一个命名捕获组，用于在重写后的路径中引用正则表达式匹配到的部分。
#
#这样，如果有一个请求的路径是`/api/service/user/info`，则经过`RewritePath`处理后，请求会被转发到`http://example.backend.com/user/info`。