spring:
  cloud:
    gateway:
      routes:
        - id: before_route
          uri: http://httpbin.org:80
          predicates:
            - Before=2023-12-31T23:59:59Z


# 和 after 类似,这个是反的,在指定时间之前是可以访问的,在指定时间之后是访问不了的