server:
  port: 12020

spring:
  application:
    name: service-gateway
  profiles:
    active: eureka-client,redis-limitconfig
  main:
    allow-circular-references: true

logging:
  level:
    root: info

# 以下是注释部分
# ignore:
#   whites:
#     - /search/*
#   loginUrl: /security/login
#   logoutUrl: /security/logout