server:
  port: 12020

spring:
  application:
    name: service-gateway
  profiles:
    active: after-router,eureka-client
  main:
    allow-circular-references: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:12000/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root: info

# 以下是注释部分
# ignore:
#   whites:
#     - /search/*
#   loginUrl: /security/login
#   logoutUrl: /security/logout