#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: limit_route
#          uri: http://httpbin.org:80
#          predicates:
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
##            - Path=/eureka-client/hi
#          filters:
#            - name: RequestRateLimiter
#              args:
#                key-resolver: '#{@hostAddrKeyResolver}'
#                redis-rate-limiter.replenish-rate: 1
#                redis-rate-limiter.burst-capacity: 1
#                redis-rate-limiter.requested-tokens: 1
spring:
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@hostAddrKeyResolver}'  # 基于IP的限流
            redis-rate-limiter.replenish-rate: 1  # 每秒请求恢复数量
            redis-rate-limiter.burst-capacity: 1 # 突发容量
            redis-rate-limiter.requested-tokens: 1 # 每个请求消耗的令牌数
      routes:
        - id: my_route
          uri: lb://eureka-client
          predicates:
            - Path=/**
  redis:
    host: 192.168.3.220
    port: 16379
    database: 5
    password: cquissE12