server:
  port: 11007

spring:
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: KJ3iDzthT_YDzRQfzjOv

  main:
    allow-bean-definition-overriding: true


#logging:
#  level:
#    root: debug

