spring:
  elasticsearch:
    uris: http://192.168.80.140:9200
#    username: elastic
#    password: Q_N3Ja+RBs3xHLhOdKz-
  main:
    allow-bean-definition-overriding: true


logging:
  level:
    root: debug
